name: Build and Test Workflow

on:
  push:
    branches:
      - "master"
      - "github-actions"
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.9.0"

      - name: Install libjemalloc-dev (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libjemalloc-dev -y

      - name: Install Dependencies
        run: |
          git clone https://github.com/cpisciotta/xcbeautify
          cd xcbeautify
          git checkout 2.0.1
          swift build -c release
          sudo cp .build/release/xcbeautify /usr/bin/xcbeautify

      - name: Build Project
        run: |
          ./generate_resources.sh
          swift build -v

      - name: Run Tests
        run: |
          set -o pipefail && xcodebuild [flags] | xcbeautify --renderer github-actions

      - name: Run Benchmarks
        run: swift package benchmark
